version: "3"

services:
  strapi:
    build:
      context: ./
    volumes:
      - ./app:/srv/app
      - ./db:/.tmp/

    labels:
      - "traefik.backend=strapi"
      - "traefik.frontend.rule=Host:intercambiostransorganicos.org"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.port=1337"
      - "traefik.enable=true"

  traefik:
      image: traefik:1.7-alpine
      depends_on:
        - strapi
      ports:
        - "80:80"
        - "443:443"
      labels:
        - "traefik.backend=traefik"
        - "traefik.frontend.rule=Host:trae.intercambiostransorganicos.org"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.port=8080"
        - "traefik.enable=true"
      restart: always
      volumes:
        - ./etc/traefik.toml:/etc/traefik/traefik.toml
        - /var/run/docker.sock:/var/run/docker.sock
        - ./etc/acme.json:/acme.json

