defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$apr1$GeChqf9F$vse2JCnKKzhQKLUoNlcEf0"]

[api]
entrypoint="dashboard"

[entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
[entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "santacruz58924@untref.edu.ar"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
domain = "intercambiostransorganicos.org"
watch = true
